module Washer {
	struct Reservation{
		string who;
		long long duration;
	};

	typedef sequence<Reservation> ReservationSeq;

	interface ReservationQueue {
		ReservationSeq reservations();
		ReservationSeq reservationsBy(in string who);
		ReservationSeq reservationWaitingTimes();
		ReservationSeq reservationWaitingTimesBy(in string who);
		
		long size();
		boolean enqueue(in string who, in long long duration);
		Reservation dequeue();
		boolean isEmpty();
		boolean remove(in long index);
	};

	interface Washer {
		long long runningTime();
		boolean on();
		boolean off();
	};
};