package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/ReservationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 15일 월요일 오후 4시 53분 51초 KST
*/

abstract public class ReservationHelper
{
  private static String  _id = "IDL:Washer/Reservation:1.0";

  public static void insert (org.omg.CORBA.Any a, kr.ac.ajou.lazybones.washerapp.Washer.Reservation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Reservation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "who",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "duration",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (kr.ac.ajou.lazybones.washerapp.Washer.ReservationHelper.id (), "Reservation", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Reservation read (org.omg.CORBA.portable.InputStream istream)
  {
    kr.ac.ajou.lazybones.washerapp.Washer.Reservation value = new kr.ac.ajou.lazybones.washerapp.Washer.Reservation ();
    value.who = istream.read_string ();
    value.duration = istream.read_longlong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, kr.ac.ajou.lazybones.washerapp.Washer.Reservation value)
  {
    ostream.write_string (value.who);
    ostream.write_longlong (value.duration);
  }

}
