package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/ReservationQueueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 2일 화요일 오후 4시 16분 02초 KST
*/

public interface ReservationQueueOperations 
{
  kr.ac.ajou.lazybones.washerapp.Washer.Reservation[] reservations ();
  boolean enqueue (kr.ac.ajou.lazybones.washerapp.Washer.Reservation reservation);
  kr.ac.ajou.lazybones.washerapp.Washer.Reservation dequeue ();
  boolean isEmpty ();
  boolean isFull ();
  boolean remove (int index);
} // interface ReservationQueueOperations
