package kr.ac.ajou.lazybones.washerapp.Washer;

/**
* kr/ac/ajou/lazybones/washerapp/Washer/ReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 10일 수요일 오후 4시 12분 23초 KST
*/

public final class ReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public kr.ac.ajou.lazybones.washerapp.Washer.Reservation value = null;

  public ReservationHolder ()
  {
  }

  public ReservationHolder (kr.ac.ajou.lazybones.washerapp.Washer.Reservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = kr.ac.ajou.lazybones.washerapp.Washer.ReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    kr.ac.ajou.lazybones.washerapp.Washer.ReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return kr.ac.ajou.lazybones.washerapp.Washer.ReservationHelper.type ();
  }

}
