package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/WasherHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 10일 수요일 오전 11시 36분 43초 KST
*/

abstract public class WasherHelper
{
  private static String  _id = "IDL:Washer/Washer:1.0";

  public static void insert (org.omg.CORBA.Any a, kr.ac.ajou.lazybones.washerapp.Washer.Washer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Washer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (kr.ac.ajou.lazybones.washerapp.Washer.WasherHelper.id (), "Washer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Washer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WasherStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, kr.ac.ajou.lazybones.washerapp.Washer.Washer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Washer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof kr.ac.ajou.lazybones.washerapp.Washer.Washer)
      return (kr.ac.ajou.lazybones.washerapp.Washer.Washer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      kr.ac.ajou.lazybones.washerapp.Washer._WasherStub stub = new kr.ac.ajou.lazybones.washerapp.Washer._WasherStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static kr.ac.ajou.lazybones.washerapp.Washer.Washer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof kr.ac.ajou.lazybones.washerapp.Washer.Washer)
      return (kr.ac.ajou.lazybones.washerapp.Washer.Washer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      kr.ac.ajou.lazybones.washerapp.Washer._WasherStub stub = new kr.ac.ajou.lazybones.washerapp.Washer._WasherStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
