package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/WasherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 10일 수요일 오후 6시 55분 53초 KST
*/

public interface WasherOperations 
{
  long runningTime ();
  boolean on ();
  boolean off ();
} // interface WasherOperations
