package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/WasherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 15일 월요일 오후 4시 53분 51초 KST
*/

public interface WasherOperations 
{
  long runningTime ();
  boolean on ();
  boolean off ();
} // interface WasherOperations
