package kr.ac.ajou.lazybones.washerapp.Washer;


/**
* kr/ac/ajou/lazybones/washerapp/Washer/WasherPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 10일 수요일 오전 11시 36분 43초 KST
*/

public abstract class WasherPOA extends org.omg.PortableServer.Servant
 implements kr.ac.ajou.lazybones.washerapp.Washer.WasherOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_reservationQueue", new java.lang.Integer (0));
    _methods.put ("on", new java.lang.Integer (1));
    _methods.put ("off", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Washer/Washer/_get_reservationQueue
       {
         kr.ac.ajou.lazybones.washerapp.Washer.ReservationQueue $result = null;
         $result = this.reservationQueue ();
         out = $rh.createReply();
         kr.ac.ajou.lazybones.washerapp.Washer.ReservationQueueHelper.write (out, $result);
         break;
       }

       case 1:  // Washer/Washer/on
       {
         boolean $result = false;
         $result = this.on ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Washer/Washer/off
       {
         boolean $result = false;
         $result = this.off ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Washer/Washer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Washer _this() 
  {
    return WasherHelper.narrow(
    super._this_object());
  }

  public Washer _this(org.omg.CORBA.ORB orb) 
  {
    return WasherHelper.narrow(
    super._this_object(orb));
  }


} // class WasherPOA
