package kr.ac.ajou.lazybones.washerapp.Washer;

/**
* kr/ac/ajou/lazybones/washerapp/Washer/WasherHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from washer.idl
* 2015년 6월 10일 수요일 오전 11시 36분 43초 KST
*/

public final class WasherHolder implements org.omg.CORBA.portable.Streamable
{
  public kr.ac.ajou.lazybones.washerapp.Washer.Washer value = null;

  public WasherHolder ()
  {
  }

  public WasherHolder (kr.ac.ajou.lazybones.washerapp.Washer.Washer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = kr.ac.ajou.lazybones.washerapp.Washer.WasherHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    kr.ac.ajou.lazybones.washerapp.Washer.WasherHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return kr.ac.ajou.lazybones.washerapp.Washer.WasherHelper.type ();
  }

}
